services:
  api:
    image: ghcr.io/tawmy/netstone.api:main
    depends_on:
      db:
        condition: service_healthy
    environment:
      AUTH_AUTHORITY: https://dev.ffxiv.id/realms/eorzea
      S3_BUCKET_NAME: netstone-api-dev
    volumes:
      - /opt/certificates/netstone-api:/mnt/cert
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: netstone.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  reverse-proxy:
    external: true

volumes:
  api_data:
    name: netstone-api-db