services:
  api:
    environment:
      OTEL_ENDPOINT_URI: http://tracing:4317
    labels:
      - dev.orbstack.domains=api.netstone.local
    ports:
      - "8085:8080"

  queue:
    labels:
      - dev.orbstack.domains=rabbitmq.local
      - dev.orbstack.http-port=15672
  
  tracing:
    image: jaegertracing/all-in-one:1.67.0
    container_name: netstone-tracing
    restart: unless-stopped
    volumes:
      - tracing_tmp:/tmp
    labels:
      - dev.orbstack.domains=tracing.netstone.local
      - dev.orbstack.http-port=16686

volumes:
  postgres_data:
    name: netstone-api-db
  rmq_data:
    name: netstone-api-queue
  tracing_tmp:
    name: netstone-tracing-tmp