services:
  api:
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /opt/certificates/netstone-api:/mnt/cert
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: netstone.eorzea.online
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  reverse-proxy:
    external: true

volumes:
  api_data:
    name: netstone-api-db