services:
  db:
    labels:
      - dev.orbstack.domains=db.api.netstone.local

  api:
    environment:
      LOGGING__LOGLEVEL__DEFAULT: Debug
      LOGGING__LOGLEVEL__ASPNETCORE: Debug
      LOGGING__LOGLEVEL__MICROSOFT.ENTITYFRAMEWORKCORE: Debug
      DATA_PROTECTION_CERTIFICATE: /mnt/cert/netstone-api
    volumes:
      - /Users/tawmy/Desktop/cert/netstone-api:/mnt/cert
    labels:
      - dev.orbstack.domains=api.netstone.local
    ports:
      - "12345:8080"

  queue:
    labels:
      - dev.orbstack.domains=rabbitmq.local
      - dev.orbstack.http-port=15672
  
  tracing:
    labels:
      - dev.orbstack.domains=tracing.netstone.local
      - dev.orbstack.http-port=16686

volumes:
  postgres_data:
    name: netstone-api-db
  rmq_data:
    name: netstone-api-queue
  tracing_tmp:
    name: netstone-tracing-tmp