services:
  db:
    labels:
      - dev.orbstack.domains=db.api.netstone.local

  api:
    image: netstone.api
    build:
      context: .
      dockerfile: NetStone.Api/Dockerfile
    environment:
      LOGGING__LOGLEVEL__DEFAULT: Debug
      LOGGING__LOGLEVEL__ASPNETCORE: Debug
      LOGGING__LOGLEVEL__MICROSOFT.ENTITYFRAMEWORKCORE: Debug
      AUTH_AUTHORITY: https://id.ffxiv.local/realms/eorzea-dev
    volumes:
      - /Users/tawmy/Desktop/cert/netstone-api:/mnt/cert
    labels:
      - dev.orbstack.domains=api.netstone.local

volumes:
  api_data:
    name: netstone-api-db