services:
  db:
    networks:
      - default
  
  api:
    image: ghcr.io/tawmy/netstone.api:main
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
    environment:
      DATA_PROTECTION_CERTIFICATE: /mnt/cert/data-protection
    volumes:
      - /root/cert/netstone-api:/mnt/cert
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: netstone.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"
  
  queue:
    labels:
      caddy: queue.netstone.tawmy.dev
      caddy.basic_auth.wsYZs7PMxNUwnxWRaDYRW9b28pjYk4dW: ${RABBITMQ_PASSWORD_HASHED}
      caddy.reverse_proxy: "{{upstreams 15672}}"
    networks:
      - default
      - reverse-proxy
  
  tracing:
    labels:
      caddy: tracing.netstone.tawmy.dev
      caddy.basic_auth.xBsJjxJgVAxVeurUXLqvJYqsVoBfogmt: ${TRACING_PASSWORD_HASHED} # 1password entry has instructions
      caddy.reverse_proxy: "{{upstreams 16686}}"
    networks:
      - default
      - reverse-proxy

networks:
  reverse-proxy:
    external: true

volumes:
  api_data:
    name: netstone-api-db
  rmq_data:
    name: netstone-api-queue
  tracing_tmp:
    name: netstone-api-tracing-tmp