services:
  db:
    image: postgres:16.4-alpine
    container_name: netstone.api-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=netstone-api
      - POSTGRES_USER=netstone-api
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d netstone-api -U netstone-api" ]
      interval: 5s
      timeout: 4s
      retries: 5
  api:
    image: netstone.api
    container_name: netstone.api
    restart: unless-stopped
    build:
      context: .
      dockerfile: NetStone.Api/Dockerfile
    environment:
      AUTH_AUDIENCE: netstone.api
      AUTH_AUTHORITY: https://auth.tawmy.dev/realms/xiv
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      CONNECTION_STRING: Host=db;Database=netstone-api;Username=netstone-api;Password=${DB_PASSWORD}
      RABBITMQ_HOST: "rabbitmq://queue"
      RABBITMQ_USERNAME:
      RABBITMQ_PASSWORD:
  queue:
    image: rabbitmq:4-management
    container_name: netstone.api-queue
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    volumes:
      - rmq_data:/var/lib/rabbitmq